### ISSUE TITLE
Next build is broken

### ISSUE THREAD

**Issue by jarrah42** [eclipse/eavp#37] opened 2016-04-15 18:44 UTC
Does anyone know why?

**Comment by SmithRWORNL** [comment] 2016-04-15 19:53
I broke it when I added the references to the internal browser in ParaView, since org.eclipse.ui.internal.browser isn't in the target. I'm resolving it now, but we should talk about where the EAVP build emails are going, since it's been down for quite a while.

**Comment by jarrah42** [comment] 2016-04-15 20:40
The emails weren't going anywhere. They should be sent to eave-dev@eclipse.org now.

**Comment by SmithRWORNL** [comment] 2016-04-15 20:51
I'm having trouble locating the relevant options in ICE's target, so Jay said to put the package here so he can figure it out. The missing package is org.eclipse.ui.internal.browser from the http://download.eclipse.org/releases/mars update site.

**Comment by jarrah42** [comment] 2016-04-18 13:11
You should not be referencing an internal package.

**Comment by SmithRWORNL** [comment] 2016-04-18 13:29
I haven't found a way to explicitly reference the internal web browser without it. We could use IWebBrowser from org.eclipse.ui.browser, but then we can no longer guarantee that we're getting an internal browser rather than the default browser set by the user. Is it acceptable that the ParaView web visualizer might pop up in Firefox instead of inside of ICE?

**Comment by jarrah42** [comment] 2016-04-18 14:12
You should respect the user's web browser preference setting. Not to do so is bad practice IMHO.

**Comment by jayjaybillings** [comment] 2016-04-18 21:29
I agree, but, @SmithRWORNL, you raise a very good question. 

In general, ICE does not allow anything to open in an external window regardless of user preference. That is by design because it is an *integrated* environment. However, that does not mean that you should do something like

new org.eclipse.ui.internal.browser.WebBrowserEditor()

or whatever. Calling internal API is never a good idea. Even in cases where the whole community is doing it, it still may not be a good idea because developers can change that API at will, which leads to bugs in our code. Instead, you should get the browser part you need from the IWorkbenchBrowserSupport using the proper id. For the browser above, its ID is "org.eclipse.ui.browser.editor" according to 

http://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/internal/browser/WebBrowserEditor.java

Information on the IWorkbenchBrowserSupport interface is available from:

http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fhelp%2Fbrowser%2Fpackage-summary.html
http://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/bundles/org.eclipse.ui.browser/src/org/eclipse/ui/browser/BrowserFactory.java

Also, it is probably better to figure out the right way to do it like this than it is to use SWT's Browser like ICE does in its ICEResourcePage. That code used to break all the time and I'm sure it still would if anyone used it regularly. ;-)

Let me end by saying too that EAVP is its own project now: We can't do things with EAVP purely to serve ICE, we have to do what is best for EAVP. That means that we need to clean this up the best we can and ICE will deal with it. Most likely the design is one where clients can provide a default id for a browser and EAVP would pick up that property to determine which browser to draw.

**Comment by SmithRWORNL** [comment] 2016-04-18 21:54
@jayjaybillings 
I've got a solution that launches the user's selected browser instead of explicitly calling the internal web browser. However, the original issue still isn't resolved, as the build is having just as much trouble finding org.eclipse.ui.browser as it was org.eclip.ui.internal.browser, although the former actually appears to be in the target already.

**Comment by SmithRWORNL** [comment] 2016-04-18 21:56
I didn't see @jarrah42 's pull request, so this may be resolved by what I just pushed to my branch. I'll test it tomorrow.

**Comment by SmithRWORNL** [comment] 2016-04-19 15:13
Fixed by commit d317fda4e6f44f2f9f7019243698bc503053ef9c.

**Closed by SmithRWORNL** 2016-04-19 15:13 UTC
Labels: bug
