### ISSUE TITLE
Geometry Import Code does not give good error codes to user

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#113] opened 2016-07-29 20:36 UTC
The import functionality often just tries to import, and does nothing when errors are thrown to tell the user what happened. There needs to be an error dialog or some other way of communicating the different possible issues that can come up when importing geometries.

**Comment by SmithRWORNL** [comment] 2016-08-10 13:13
This is a duplicate of #98 , which also deals with giving the user error messages when a .stl file import fails.

**Closed by SmithRWORNL** 2016-08-10 13:13 UTC
Labels: bug, duplicate, enhancement
